[package]
name = "lorchestre"
version = "0.0.0"
description = "The only music player you'll ever need"
authors = ["luxluth"]
edition = "2021"
license = "GPL-3.0"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# tauri-plugin-fs = "2.0.0-beta.7"
lorconf = { path = "../conf" }
tauri = { version = "2.0.0-beta", features = [
  "macos-private-api",
  "linux-ipc-protocol",
] }
reqwest = "0.12.5"
