[package]
name = "mu"
version = "0.0.0"
description = "Mu music"
authors = ["luxluth"]
edition = "2021"
license = "GPL-3.0"


[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [
  "macos-private-api",
  "protocol-asset",
  "linux-ipc-protocol",
] }
tauri-plugin-shell = "2.0.0-beta"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2.0.0-beta.7"
muconf = { path = "../conf" }
