[package]
name = "lorchestre"
version = "0.1.0"
edition = "2024"

[dependencies]
alrc = "0.1.0"
bincode = { git = "https://git.sr.ht/~stygianentity/bincode" }
dirs = "6.0.0"
env_logger = "0.11"
fuzzy-matcher = "0.3.7"
glob = "0.3.2"
lofty = "0.25"
log = "0.4"
md5 = "0.8"
mime_guess = "2.0.5"
mtk = { git = "https://github.com/luxluth/mtk.git", version = "0.0.1" }
rodio = { version = "0.22.2", features = ["symphonia-all"] }
rust-i18n = "4.2"
tokio = { version = "1.53", features = ["full"] }
symphonia = { version = "0.6.1", features = ["all"] }
rfd = "0.17.2"
arc-swap = "1.9.2"

[features]
default = []
debug = ["mtk/debugger"]
