[package]
name = "orchestre"
version = "0.1.0"
edition = "2024"

[dependencies]
alrc = "0.1.0"
bincode = { git = "https://git.sr.ht/~stygianentity/bincode" }
dirs = "7.0.0"
env_logger = "0.11"
fuzzy-matcher = "0.3.7"
glob = "0.3.4"
lofty = "0.25"
log = "0.4"
md5 = "0.8"
mime_guess = "2.0.5"
# mtk-rs = "=0.1.0-beta.2"
mtk-rs = { git = "https://github.com/luxluth/mtk.git", branch = "master" }
rodio = { version = "0.22.2", features = ["symphonia-all"] }
rust-i18n = "4.2"
tokio = { version = "1.53", features = ["full"] }
symphonia = { version = "0.6.1", features = ["all"] }
rfd = "0.17.2"
arc-swap = "1.9.2"
kmeans_colors = "0.7.1"
palette = "0.7.7"
image = "0.25.10"

[features]
default = []
debug = ["mtk-rs/debugger"]
